language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

install:
  - sudo apt-get install -y portaudio19-dev python-all-dev --no-install-recommends
  - sudo apt-get install -y lilv-utils calf-plugins guitarix --no-install-recommends
  - pip3 install sphinx
  - pip3 install cffi
  - python setup.py develop
  - pip3 install pytest pytest-cov

script:
  - lv2ls
  - make test
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
