language: python

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"

install:
  - pip3 install coverage

script:
  - coverage3 run --source=pluginsmanager setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
