language: python

python:
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "nightly"

sudo: required

install:
  - apt-get install lilv-utils
  - pip3 install coveralls
  - pip3 install cffi
  - pip3 install JACK-Client

script:
  - cd ..
  - mkdir data
  - cd data
  - mkdir test
  - cd ../PluginsManager
  - coverage3 run --source=pluginsmanager setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
