language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

sudo: required

jobs:
  include:
    - stage: doc
      script:
        - make install-docs-requirements
        - make docs

install:
  - sudo apt-get install -y portaudio19-dev python-all-dev --no-install-recommends
  - sudo apt-get install -y lilv-utils calf-plugins guitarix --no-install-recommends
  - sudo apt-get install -y lv2-dev --no-install-recommends
  - pip3 install -U setuptools
  - pip3 install sphinx
  - pip3 install cffi
  - python setup.py develop
  - pip3 install pytest pytest-cov
  - make install-tests-requirements

script:
  - lv2ls
  - make test
  - #make test-docs
  - #pytest --doctest-modules

after_success:
  - bash <(curl -s https://codecov.io/bash)
