language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

sudo: required

install:
  - sudo apt-get install -y lilv-utils calf-plugins guitarix --no-install-recommends
  - pip3 install coveralls
  - pip3 install cffi
  - pip3 install JACK-Client

script:
  - lv2ls
  - cd ..
  - mkdir data
  - cd data
  - mkdir test
  - cd ../PluginsManager
  - coverage3 run --source=pluginsmanager setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
